services:
  postgres:
    container_name: postgres
    image: postgres:17-alpine
    ports:
      - 5432:5432
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=sigle_password
      - POSTGRES_USER=sigle_user
      - POSTGRES_DB=sigle_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d sigle_db -U sigle_user"]
      interval: 1s
      timeout: 5s
      retries: 10

  server:
    build:
      context: ./
      dockerfile: ./apps/server-next/Dockerfile.dev
    restart: always
    ports:
      - "3001:3001"
      - "9080:9080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://sigle_user:sigle_password@postgres:5432/sigle_db?sslmode=disable
    develop:
      watch:
        - path: ./apps/server-next/package.json
          action: rebuild
        - path: ./apps/server-next/
          target: /app/apps/server-next
          action: sync
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
