allowBuilds:
  "@parcel/watcher": false
  "@prisma/engines": true
  "@reown/appkit": false
  "@sentry/cli": false
  "bigint-buffer": false
  "bufferutil": false
  "core-js": false
  "esbuild": false
  "keccak": false
  msw: false
  "prisma": false
  "protobufjs": false
  "secp256k1": false
  "sharp": false
  "tiny-secp256k1": false
  "utf-8-validate": false
blockExoticSubdeps: true
strictDepBuilds: true
minimumReleaseAge: 1440 # 1 day
packages:
  - apps/*
  - packages/*
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.2.4
  vitest: 4.1.10
  vite-plus: 0.2.4
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
minimumReleaseAgeExclude:
  - vite-plus
  - "@voidzero-dev/*"
  - oxlint
  - "@oxlint/*"
  - oxlint-tsgolint
  - "@oxlint-tsgolint/*"
  - oxfmt
  - "@oxfmt/*"
  - vitest
  - "@vitest/*"
