ARG NODE_VERSION=24
FROM node:${NODE_VERSION}-alpine AS base

WORKDIR /app

ENV APP_NAME="custom-domain"

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME/bin:$PATH"
RUN apk add --no-cache git
COPY --link ./package.json ./
RUN corepack enable pnpm
RUN TURBO_VERSION=$(grep -o '"turbo": "[^"]*' package.json | cut -d'"' -f4) && \
    pnpm install turbo@${TURBO_VERSION} --global
RUN pnpm install @dotenvx/dotenvx@^2 --global

# --- Turbo stage ---

FROM base AS builder
WORKDIR /app
COPY . .
RUN turbo prune @sigle/$APP_NAME --docker

# --- Build stage ---

FROM base AS installer
WORKDIR /app

# First install dependencies
COPY .gitignore .gitignore
COPY --from=builder /app/out/json/ .
COPY --from=builder /app/out/pnpm-lock.yaml ./pnpm-lock.yaml
COPY --from=builder /app/out/pnpm-workspace.yaml ./pnpm-workspace.yaml
RUN npm pkg delete scripts.prepare
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile

# Copy full sources
COPY --from=builder /app/out/full/ .
COPY --from=builder /app/apps/contracts ./apps/contracts
COPY --from=builder /app/apps/contracts-next ./apps/contracts-next
COPY ./apps/$APP_NAME/.env.development* ./apps/$APP_NAME/
COPY turbo.json turbo.json

WORKDIR /app/apps/$APP_NAME

CMD turbo run dev
