/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["health.get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/protected/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["protected.me"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/protected/drafts": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List drafts
     * @description List the current user drafts, most recently updated first.
     */
    get: operations["drafts.list"];
    put?: never;
    /**
     * Create a draft
     * @description Create a new draft, optionally seeded with the provided fields.
     */
    post: operations["drafts.create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/protected/drafts/{draftId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get a draft */
    get: operations["drafts.get"];
    put?: never;
    post?: never;
    /** Delete a draft */
    delete: operations["drafts.delete"];
    options?: never;
    head?: never;
    /**
     * Update a draft
     * @description Partially update a draft following JSON Merge Patch semantics: omitted fields are left unchanged and `null` clears nullable fields.
     */
    patch: operations["drafts.update"];
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    sigle_api_TooManyRequestsEncoded: {
      /** @enum {string} */
      _tag: "TooManyRequests";
      message: string;
      retryAfterMillis: number;
    };
    sigle_api_InternalServerErrorEncoded: {
      /** @enum {string} */
      _tag: "InternalServerError";
      message: string;
    };
    sigle_api_UnauthorizedEncoded: {
      /** @enum {string} */
      _tag: "Unauthorized";
      message: string;
    };
    CreateDraftPayload: {
      title?: string;
      content?: string;
      metaTitle?: string | null;
      metaDescription?: string | null;
      coverImage?: string | null;
      tags?: string[];
      canonicalUri?: string | null;
    };
    Draft: {
      id: string;
      title: string;
      content: string;
      metaTitle: string | null;
      metaDescription: string | null;
      coverImage: string | null;
      tags: string[];
      canonicalUri: string | null;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    sigle_api_ForbiddenEncoded: {
      /** @enum {string} */
      _tag: "Forbidden";
      message: string;
    };
    DraftListItem: {
      id: string;
      title: string;
      metaTitle: string | null;
      metaDescription: string | null;
      coverImage: string | null;
      tags: string[];
      canonicalUri: string | null;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    DraftListResponse: {
      results: components["schemas"]["DraftListItem"][];
      limit: number;
      offset: number;
      total: number;
    };
    Draft_1: {
      id: string;
      title: string;
      content: string;
      metaTitle: string | null;
      metaDescription: string | null;
      coverImage: string | null;
      tags: string[];
      canonicalUri: string | null;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    sigle_api_NotFoundEncoded: {
      /** @enum {string} */
      _tag: "NotFound";
      message: string;
    };
    UpdateDraftPayload: {
      /** @description Omit to keep the current value unchanged. */
      title?: string;
      /** @description Omit to keep the current value unchanged. */
      content?: string;
      /** @description Omit to keep the current value unchanged, set to null to clear it. */
      metaTitle?: string | null;
      /** @description Omit to keep the current value unchanged, set to null to clear it. */
      metaDescription?: string | null;
      /** @description Omit to keep the current value unchanged, set to null to clear it. */
      coverImage?: string | null;
      /** @description Omit to keep the current value unchanged, set to null to clear it. */
      tags?: string[] | null;
      /** @description Omit to keep the current value unchanged, set to null to clear it. */
      canonicalUri?: string | null;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  "health.get": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Success */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            success: boolean;
          };
        };
      };
      /** @description Too Many Requests */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["sigle_api_TooManyRequestsEncoded"];
        };
      };
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["sigle_api_InternalServerErrorEncoded"];
        };
      };
    };
  };
  "protected.me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Success */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            id: string;
            whitelisted: boolean;
          };
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["sigle_api_UnauthorizedEncoded"];
        };
      };
      /** @description Too Many Requests */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["sigle_api_TooManyRequestsEncoded"];
        };
      };
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["sigle_api_InternalServerErrorEncoded"];
        };
      };
    };
  };
  "drafts.list": {
    parameters: {
      query?: {
        limit?: string;
        offset?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description DraftListResponse */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DraftListResponse"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["sigle_api_UnauthorizedEncoded"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["sigle_api_ForbiddenEncoded"];
        };
      };
      /** @description Too Many Requests */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["sigle_api_TooManyRequestsEncoded"];
        };
      };
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["sigle_api_InternalServerErrorEncoded"];
        };
      };
    };
  };
  "drafts.create": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateDraftPayload"];
      };
    };
    responses: {
      /** @description Draft */
      201: {
        headers: {
          location: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Draft"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["sigle_api_UnauthorizedEncoded"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["sigle_api_ForbiddenEncoded"];
        };
      };
      /** @description Too Many Requests */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["sigle_api_TooManyRequestsEncoded"];
        };
      };
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["sigle_api_InternalServerErrorEncoded"];
        };
      };
    };
  };
  "drafts.get": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        draftId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Draft */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Draft_1"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["sigle_api_UnauthorizedEncoded"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["sigle_api_ForbiddenEncoded"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["sigle_api_NotFoundEncoded"];
        };
      };
      /** @description Too Many Requests */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["sigle_api_TooManyRequestsEncoded"];
        };
      };
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["sigle_api_InternalServerErrorEncoded"];
        };
      };
    };
  };
  "drafts.delete": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        draftId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description <No Content> */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["sigle_api_UnauthorizedEncoded"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["sigle_api_ForbiddenEncoded"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["sigle_api_NotFoundEncoded"];
        };
      };
      /** @description Too Many Requests */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["sigle_api_TooManyRequestsEncoded"];
        };
      };
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["sigle_api_InternalServerErrorEncoded"];
        };
      };
    };
  };
  "drafts.update": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        draftId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateDraftPayload"];
      };
    };
    responses: {
      /** @description Draft */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Draft_1"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["sigle_api_UnauthorizedEncoded"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["sigle_api_ForbiddenEncoded"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["sigle_api_NotFoundEncoded"];
        };
      };
      /** @description Too Many Requests */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["sigle_api_TooManyRequestsEncoded"];
        };
      };
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["sigle_api_InternalServerErrorEncoded"];
        };
      };
    };
  };
}
