[build]
builder = "DOCKERFILE"
watchPatterns = ["/apps/server-next/**"]
dockerfilePath = "/apps/server-next/Dockerfile"

[deploy]
numReplicas = 1
healthcheckPath = "/health"
healthcheckTimeout = 300
sleepApplication = true
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
