# fly.toml file generated for sigle on 2021-02-26T13:16:43+01:00

app = "sigle-staging"

kill_signal = "SIGINT"
kill_timeout = 5

[experimental]
  private_network = true

[[services]]
  internal_port = 3000
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = "80"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.http_checks]]
    grace_period = "1s"
    interval = "10s"
    method = "get"
    path = "/api/health"
    protocol = "http"
    restart_limit = 5
    timeout = "2s"
    tls_skip_verify = false
