export const sigleConfig = {
  env: process.env.NODE_ENV,
  isServer: typeof window === 'undefined',
  appUrl: process.env.APP_URL as string,
  apiUrl: process.env.API_URL,
  landingUrl: 'https://www.sigle.io',
  sentryDsn: process.env.NEXT_PUBLIC_SENTRY_DSN,
  fathomSiteId: process.env.FATHOM_SITE_ID,
  posthogToken: process.env.NEXT_PUBLIC_POSTHOG_TOKEN,
  githubUrl: 'https://github.com/sigle/sigle',
  twitterUrl: 'https://twitter.com/sigleapp',
  discordUrl: 'https://discord.gg/X2Dbz3xbrs',
  messengerUrl: 'https://m.me/sigleapp',
  documentationUrl: 'https://docs.sigle.io',
  explorerGuildUrl: 'https://www.explorerguild.io',
  feedbackUrl: 'https://sigle.canny.io/feature-requests',
  blogUrl: 'https://app.sigle.io/sigle.btc',
  gammaUrl: 'https://gamma.io/collections/the-explorer-guild',
  gumroadUrl: 'https://sigle.gumroad.com/l/sigle',
  email: 'sigle@protonmail.com',
};
