export enum Goals {
  LOGIN = 'IHBJQCC0',
  LEGACY_LOGIN = 'IYE6COYQ',
  LOGIN_SIGN_MESSAGE = 'FV12NYMQ',
  CREATE_NEW_STORY = 'WYESYDDJ',
  PUBLISH = 'PYKUM6ZG',
  FREE_USERNAME_CREATED = 'OR1RD9A7',
}
