name: "Setup the monorepo"
description: "Setup the monorepo"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v6

    - name: Cache turbo build setup
      uses: actions/cache@v4
      with:
        path: ${{ github.workspace }}/.turbo
        key: ${{ runner.os }}-turbo-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-turbo-

    - uses: pnpm/action-setup@v4

    - name: Use Node.js 22
      uses: actions/setup-node@v6
      with:
        node-version: 22
        cache: "pnpm"

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
