name: "Setup the monorepo"
description: "Setup the monorepo"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v7

    - name: Cache turbo build setup
      uses: actions/cache@v6
      with:
        path: ${{ github.workspace }}/.turbo
        key: ${{ runner.os }}-turbo-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-turbo-

    - name: Use Node.js and pnpm
      uses: pnpm/setup@v2
      with:
        cache: true
        install: false

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
